name: Cross-Platform Builds

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install Dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y gcc g++ cmake make

      - name: Install Dependencies (MacOS)
        if: matrix.os == 'macos-latest'
        run: brew install cmake

      - name: Install Dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

      - name: Configure and Build
        run: |
          cmake -B build
          cmake --build build --config Release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: binaries-${{ matrix.os }}
          path: build/*

  build-freebsd:
    runs-on: ubuntu-latest
    container:
      image: freebsd/freebsd:14
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pkg update
          pkg install -y clang cmake make

      - name: Configure and Build
        run: |
          cmake -B build-freebsd
          cmake --build build-freebsd --config Release

      - name: Upload FreeBSD Artifact
        uses: actions/upload-artifact@v3
        with:
          name: freebsd-binaries
          path: build-freebsd/libiso8583.so

  release:
    needs: [build, build-freebsd]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - name: Download All Build Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Generate Changelog
        id: changelog
        run: echo "CHANGELOG=$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:'- %s' | tr '\n' '\n')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            artifacts/binaries-ubuntu-latest/*
            artifacts/binaries-macos-latest/*
            artifacts/binaries-windows-latest/*
            artifacts/freebsd-binaries/libiso8583.so
          draft: true
          tag_name: ${{ github.ref }}
          name: "Release ${{ github.ref_name }}"
          fail_on_unmatched_files: true
          body: |
            ## Release ${{ github.ref_name }}

            **New Features & Fixes**
            ${{ env.CHANGELOG }}
