name: Cross-Platform Builds

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install Dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y gcc g++ cmake make

      - name: Install Dependencies (MacOS)
        if: matrix.os == 'macos-latest'
        run: brew install cmake

      - name: Install Dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

      - name: Configure and Build
        run: |
          cmake -B build
          cmake --build build --config Release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: binaries-${{ matrix.os }}
          path: build/*

  build-windows-mingw:
    runs-on: windows-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install MinGW
        run: choco install mingw --force

      - name: Configure and Build with MinGW
        run: |
          cmake -G "MinGW Makefiles" -B build-mingw
          cmake --build build-mingw --config Release

      - name: Upload Windows MinGW Build
        uses: actions/upload-artifact@v3
        with:
          name: windows-mingw-binaries
          path: build-mingw/iso8583.dll

  build-freebsd:
    runs-on: ubuntu-latest
    container:
      image: freebsd/freebsd:14
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pkg update
          pkg install -y clang cmake make

      - name: Configure and Build
        run: |
          cmake -B build-freebsd
          cmake --build build-freebsd --config Release

      - name: Upload FreeBSD Artifact
        uses: actions/upload-artifact@v3
        with:
          name: freebsd-binaries
          path: build-freebsd/libiso8583.so

  release:
    needs: [build, build-windows-mingw, build-freebsd]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for proper changelog generation
      
      - name: Download All Build Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Generate Version Number
        id: version
        shell: bash
        run: echo "VERSION=$(echo ${{ github.ref_name }} | sed 's/v//')" >> $GITHUB_ENV

      - name: Generate Changelog
        id: changelog
        shell: bash
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "")
          if [ -z "$LAST_TAG" ]; then
            CHANGELOG=$(git log --pretty=format:'- %s')
          else
            CHANGELOG=$(git log ${LAST_TAG}..HEAD --pretty=format:'- %s')
          fi
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        shell: bash
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            artifacts/binaries-ubuntu-latest/libiso8583.so
            artifacts/binaries-macos-latest/libiso8583.dylib
            artifacts/binaries-windows-latest/iso8583.dll
            artifacts/windows-mingw-binaries/iso8583.dll
            artifacts/freebsd-binaries/libiso8583.so
          draft: true
          tag_name: ${{ github.ref }}
          name: "Release ${{ env.VERSION }}"
          fail_on_unmatched_files: true
          body: |
            ## Release ${{ env.VERSION }}
            
            ### Changelog
            ${{ env.CHANGELOG }}
            
            ### Artifacts
            - Linux: `libiso8583.so`
            - MacOS: `libiso8583.dylib`
            - Windows (MSVC): `iso8583.dll`
            - Windows (MinGW): `iso8583.dll`
            - FreeBSD: `libiso8583.so`
